project_id = "gionpsuunfkkzzjdubfy"

[functions.google-sheets-sync]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.ml-oauth]
verify_jwt = false