project_id = "gionpsuunfkkzzjdubfy"

[functions.google-sheets-sync]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.ml-oauth]
verify_jwt = false

[functions.mercado-libre-integration]
verify_jwt = false

[functions.magalu-integration]
verify_jwt = false

[functions.ml-token-refresh]
verify_jwt = false

[functions.ml-inventory]
verify_jwt = false
